title: ROB498/599 Experimental UAS
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://rob-eaus-docs.github.io

aux_links:
  Course Github: https://github.com/rob-eaus-docs/rob-eaus-docs.github.io

math: katex

logo: "/assets/images/robotics-logo.svg"
favicon_ico: "/assets/images/favicon.png"

callouts_level: quiet # or loud 
callouts:
  highlight:
    title: Highlight
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red